In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle
import numpy as np

In [3]:
#load the dataset
data = pd.read_csv('kidney_disease.csv')
data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [4]:
onname={'age':'age',
'bp':'blood_pressure',
'sg':'specific_gravity',
'al':'albumin',
'su':'sugar',
'rbc':'red_blood_cells',
'pc':'pus_cell',
'pcc':'pus_cell_clumps',
'ba':'bacteria',
'bgr':'blood_glucose_random',
'bu':'blood_urea',
'sc':'serum_creatinine',
'sod':'sodium',
'pot':'potassium',
'hemo':'hemoglobin',
'pcv':'packed_cell_volume',
'wc':'white_blood_cell_count',
'rc':'red_blood_cell_count',
'htn':'hypertension',
'dm':'diabetes_mellitus',
'cad':'coronary_artery_disease',
'appet':'appetite',
'pe':'pedal_edema',
'ane':'anemia',
'classification':'class',
}
data=data.rename(columns=onname)
data

,id,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [5]:
data['diabetes_mellitus'] = data['diabetes_mellitus'].replace('\\t', "", regex=True)
data['diabetes_mellitus'] = data['diabetes_mellitus'].replace('\\t', "", regex=True)
data['packed_cell_volume'] = data['packed_cell_volume'].replace('\\t', "", regex=True)
data['white_blood_cell_count'] = data['white_blood_cell_count'].replace('\\t', "", regex=True)
data['red_blood_cell_count'] = data['red_blood_cell_count'].replace('\\t', "", regex=True)
data['class'] = data['class'].replace('\\t', "", regex=True)
data['coronary_artery_disease'] = data['coronary_artery_disease'].replace('\\t', "", regex=True)
data['packed_cell_volume']=np.where(data['packed_cell_volume']=='?',np.nan ,data['packed_cell_volume'])
data['red_blood_cell_count']=np.where(data['red_blood_cell_count']=='?',np.nan ,data['red_blood_cell_count'])
data['white_blood_cell_count']=np.where(data['white_blood_cell_count']=='?',np.nan ,data['red_blood_cell_count'])
data['packed_cell_volume'] = data['packed_cell_volume'].astype(float)
data['diabetes_mellitus']=data['diabetes_mellitus'].str.strip()
data['red_blood_cell_count'] = data['red_blood_cell_count'].astype(float)
data['white_blood_cell_count'] = data['white_blood_cell_count'].astype(float)

In [6]:
data

,id,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44.0,5.2,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38.0,NaN,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31.0,NaN,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32.0,3.9,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35.0,4.6,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47.0,4.9,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54.0,6.2,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49.0,5.4,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51.0,5.9,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53.0,6.1,6.1,no,no,no,good,no,no,notckd

## Preprocess Data

### Drop irrelavant Feature.

In [7]:
data=data.drop(['id'],axis=1)

### Impute missing value

In [8]:
cat=[]
num=[]
for i in data.columns:
    if data[i].dtype=="object":
        cat.append(i)
    else:
        num.append(i)
print(cat) 
print(num)

['red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria', 'hypertension', 'diabetes_mellitus', 'coronary_artery_disease', 'appetite', 'pedal_edema', 'anemia', 'class']
['age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar', 'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium', 'potassium', 'hemoglobin', 'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count']

In [9]:
from sklearn.impute import SimpleImputer
simple_imputer = SimpleImputer(strategy='most_frequent')
data[cat] = simple_imputer.fit_transform(data[cat])

In [ ]:
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=3)
data[num] = knn_imputer.fit_transform(data[num])

In [ ]:
    
pickle.dump(knn_imputer, open("knn_imputer.pkl", "wb"))
    
pickle.dump(simple_imputer, open("simple_imputer.pkl", "wb"))

In [12]:
cat

['red_blood_cells',
 'pus_cell',
 'pus_cell_clumps',
 'bacteria',
 'hypertension',
 'diabetes_mellitus',
 'coronary_artery_disease',
 'appetite',
 'pedal_edema',
 'anemia',
 'class']

In [13]:
for i in range (len(cat)):
    print(data[cat[i]].unique())

['normal' 'abnormal']
['normal' 'abnormal']
['notpresent' 'present']
['notpresent' 'present']
['yes' 'no']
['yes' 'no']
['no' 'yes']
['good' 'poor']
['no' 'yes']
['no' 'yes']
['ckd' 'notckd']

In [14]:
from sklearn.preprocessing import LabelEncoder
import pickle

encoders = {}

for col in cat:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    encoders[col] = le   # store encoder per column

# Save dictionary of encoders
pickle.dump(encoders, open("encoders.pkl", "wb"))

In [15]:
data.head()

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,1,1,0,0,121.0,...,44.0,5.200000,5.200000,1,1,0,0,0,0,0
1,7.0,50.0,1.020,4.0,0.0,1,1,0,0,123.0,...,38.0,5.200000,5.200000,0,0,0,0,0,0,0
2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,423.0,...,31.0,4.366667,4.366667,0,1,0,1,0,1,0
3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,117.0,...,32.0,3.900000,3.900000,1,0,0,1,1,1,0
4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,106.0,...,35.0,4.600000,4.600000,0,0,0,0,0,0,0

## Split and scale

In [ ]:
## DiVide the dataset into indepent and dependent features
X=data.drop('class',axis=1)
y=data['class']

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
with open('scalar.pkl', 'wb') as f:
    pickle.dump(scaler, f)

## Random Forest Implementation

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfmodel = RandomForestClassifier(n_estimators=100, random_state=42)
rfmodel.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
pickle.dump(rfmodel, open("random_forest_model.pkl", "wb"))